### ISSUE TITLE
Game design requirements

### ISSUE THREAD

**Issue by davmmeyer** [nadcock/CSC478-SOC-Game#2]
♣	Game initialization, setup (board layout, player setup), ending, tear down
♣	Game play requirements (rules, turns, point system)
What can someone do on their turn (decision)

**Comment by nadcock** [comment]
This is blocked

**Comment by nadcock** [comment]
Requirements Doc: https://docs.google.com/a/nicksemail.com/document/d/10ZdPqDuBsquep6k707zK6w5OIK1Nl83giMugLYsit_M/edit?usp=sharing
