### ISSUE TITLE
Game play pieces

### ISSUE THREAD

**Issue by davmmeyer** [nadcock/CSC478-SOC-Game#3]
♣	8 unique tiles (water (w/ports), water (no ports), hills (brick), forest (lumber), mountains (ore), fields (grain), pasture (wool), desert (nothing) 
♣	4 unique pieces 
♣	Dice (2x 6-sided dice)
♣	What are the rules around the tiles, actors, robbers, etc.
How many tiles, cards, characters, tile types, robber

**Comment by mpolsgrove** [comment]
https://docs.google.com/document/d/1Z4HRK7owQwkwY0rChOXMqoqYYAyd1v_sRI2i2Zfs--I/edit?usp=sharing
